export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SAVE_IDEA_START = 'SAVE_IDEA_START';
export const SAVE_IDEA_SUCCESS = 'SAVE_IDEA_SUCCESS';
export const SAVE_IDEA_FAIL = 'SAVE_IDEA_FAIL';

export const FETCH_IDEAS_START = 'FETCH_IDEAS_START';
export const FETCH_IDEAS_SUCCESS = 'FETCH_IDEAS_SUCCESS';
export const FETCH_IDEAS_FAIL = 'FETCH_IDEAS_FAIL';

export const FETCH_IDEA_START = 'FETCH_IDEA_START';
export const FETCH_IDEA_SUCCESS = 'FETCH_IDEA_SUCCESS';
export const FETCH_IDEA_FAIL = 'FETCH_IDEA_FAIL';

export const DELETE_IDEA_START = 'DELETE_IDEA_START';
export const DELETE_IDEA_SUCCESS = 'DELETE_IDEA_SUCCESS';
export const DELETE_IDEA_FAIL = 'DELETE_IDEA_FAIL';

export const UPDATE_INIT = 'UPDATE_INIT';
export const UPDATE_IDEA_START = 'UPDATE_IDEA_START';
export const UPDATE_IDEA_SUCCESS = 'UPDATE_IDEA_SUCCESS';
export const UPDATE_IDEA_FAIL = 'UPDATE_IDEA_FAIL';
